### ISSUE TITLE
adding stardict format to the three Smith Dictionaries?

### ISSUE THREAD

**Issue by jiang-qian** [latin-dict/Smith1854#1]
First of all, thank you so much for making these beautiful dictionaries! I am using the LSJ and Lewis-Short on both my phone (goldendict) and my computer (ditto).

I would greatly appreciate it, if you could also release the stardict format file for the three dictionaries edited by Smith (Geography, Biography and Antiquity). I tried to use pyglossary to convert the slob file to stardict so that I can use them in on phone but the conversion always misses many words and messed up the format. Even on desktop (I use linux), my distro's version of Goldendict cannot read slob. 

It would be an immense help if you could provide the stardict format for these three dictionaries, just as you did for the LSJ and Lewish-Short! Thank you so much for your help!

By the way, there is a version of Autenrieth's Homeric dictionary on Perseus, would it be possible to convert that to offline dictionary format, too?

Again, thank you for making all these great dictionaries more accessible!

**Comment by nikita-moor** [comment]
Hi @jiang-qian!

### Smith's dictionaries

I'll take a look, it shouldn't be difficult to make Stardict version.

### Autenrieth's Homeric dictionary

The main problem with Perseus dictionaries is to find source files. They publish them in different places and not all the Perseus' texts are licensed for free distribution (i.e. Public Domain or Creative Commons). Website [LSJ.gr](https://lsj.gr) doesn't have Autenrieth's dictionary, so it's very likely that source files are not available.

Also, I am more interested in Latin dictionaries, so this request is a low priority.

> Even on desktop (I use linux), my distro's version of Goldendict cannot read slob.

You could try [alternative binaries](https://latin-dict.github.io/docs/howto.html), but it cannot be guaranteed although.

**Comment by jiang-qian** [comment]
Thanks a lot for looking into making the stardict version for the three Smith dictionaries! That will really help me on mobile.

For Homer dictionary, I understand the problem. In fact I once wrote to then Perseus people about copyright and availability of xml sources of the works available on their site. What they say is that they have three categories of files: 

1.those published before 1920s which means they are out of copyright. There are also some works that we're published afterwards but the publishers didn't legally assert the copyright. These works they provide the xml files.

2. There are works that are definitely still in copyright but they receive special permission from the publishers to use on websites. These are not offered in xml format.

3. There are those whose copyright status is unknown. These they also doesn't offer downloads.

For the Homer dictionary, it was published in 19 century, so it is unclear why it is not included. But that's ok.

I'll try to compile Goldendict myself. I use linux and they don't seem to offer binary for it. But the stardict format is still helpful for mobile, since it gives so many more choices to read it.

Thanks again for making these great stardict dictionaries! I particularly like that your dictionaries are beautifully formatted!

**Comment by jiang-qian** [comment]
In fact, if you could release the code with which you convert Perseus xml to stardict, that would obviate the need for me to bug you again for dictionaries of this format. Is the code complicated or proprietary?

**Comment by jiang-qian** [comment]
I'll ask Perseus people why Homer dictionary xml is not included.

**Comment by nikita-moor** [comment]
I have added files in StarDict format to every Smith's dictionary:

- [antiquities](https://github.com/latin-dict/Smith1890/releases/tag/v1.0)
- [biography](https://github.com/latin-dict/Smith1873/releases/tag/v1.0)
- [geography](https://github.com/latin-dict/Smith1854/releases/tag/v1.0)

Could you, please, check them?

> In fact, if you could release the code with which you convert Perseus xml to stardict, that would obviate the need for me to bug you again for dictionaries of this format. Is the code complicated or proprietary?

I don't have enough time to polish the code, publish it, and regularly upload on GitHub.

I use [PyGlossary](https://github.com/ilius/pyglossary/) to produce files in StarDict format. Something like this:

```py
import pyglossary
glos = pyglossary.Glossary()
glos.addEntry("cat", "tender animal")
glos.addEntry("dog", "noisy animal")
glos.write("my-dict.ifo", "Stardict", sametypesequence="h")
```

**Comment by jiang-qian** [comment]
They seem to work! I don't know why they didn't work when I used pyglosssart command line to convert, but these three you provided seem to work!

I will test it extensively and let you know if any problem pops up!

Thank you so much for helping me out! I really appreciate it!

**Comment by nikita-moor** [comment]
Reopen this issue or create a new one if you find any error.
